#cloud-config

coreos:
  etcd:
    name: ${node}
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/4d31e897e9f44ed5c945450b1ccfa40f
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $(ip}:4001
    peer-addr: $(ip}:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start


ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDl38xoZjilX4XKiIG4mnFGll4WcXIk14Og/tI7u78lZ3i2gwM7hG6xntdjfgd7ZS1388GlpBIRzvQGNExqK8eajRYce6xt/29WvAyoYLBEiUjbCFtUzQjE0qKy3MlRlW5Pn7J89uQfxFzfEeHkKH7NBkNkQinKbBLpmPs9BAj3UiGzC/y7GXtxPTB6GUuVFMlaxLETQZLGur5vhD7ZwJImsp1vK4NNRcoQkpC8AUrfjYLDCnFNi86OmGgg6A2CauG+rUIqkDGCNcLg/Aejr0GHY8Yw74kZ4VQbweYuS0O6T4OVFwT/SnDHy8WxE+liJ2VNq9sT4rlWYk1AUPocNh6t
